### ISSUE TITLE
Not working with password protected UEFI

### ISSUE THREAD

**Issue by TID41** [enielrodriguez/cctk-batterycfg#4]
Hello,
I responded to the message you sent in the Acer thread asking for my input via email, but for some reason it never showed up here. I don't know why that did not work.

Initially I wrote that the applet properly reports the status of the battery limit on my Dell, but the options to change it do not work. I realized that I have a password protecting the UEFI settings, which means the cctk utility must send this password to change the settings. The parameter --ValSetupPwd='password' must be passed to cctk, where 'password' is the actual password of course. I tried it with and without the half quotes from the terminal, and in both cases it worked.

I made a few edits to the applet, adding a password field to the settings dialog, and it will pass that password when issuing commands to change the mode. It works well, though with a few caveats.

I tried at first to have it only send the password command when the user has entered some data in the password field, but it didn't work, which is not surprising given that I do not actually know QML. So, I did the lazy thing and just had it send the password command even if the password string is null. I don't know if sending a null password will work when there is no password set. 

Also, the password is not saved between sessions (which can be considered a feature depending on your perspective). If it were saved, it would probably be in plain text.

It also requests the superuser password on bootup, which the Acer version does not. I am not sure if this can easily be mitigated or not.

Here is the applet with the edits, in case you want to use it.

[acer-battery-limit-switcher.zip](https://github.com/enielrodriguez/cctk-batterycfg/files/13181742/acer-battery-limit-switcher.zip)

**Comment by enielrodriguez** [comment]
Thanks for the contribution. I will complete the functionality by including saving between sessions.  
As for the root authorization request, it is more complicated, I understand that cctk requires it even to querying the status of a settings.
