### ISSUE TITLE
CCTK always requires root permissions to run

### ISSUE THREAD

**Issue by TID41** [enielrodriguez/cctk-batterycfg#8]
I followed the guide listed to allow CCTK to run as root without a password prompt. If I untick the box for "needs SUDO," however, the CCTK application still refuses to run, so the plasmoid cannot read or set the battery charge config.

From the terminal, I can now use 

`sudo /opt/dell/dcc/cctk --PrimaryBattChargeCfg`

and it runs and displays the charge config without me being prompted for the password, but _the 'sudo' command is still needed_. If I enter 

`/opt/dell/dcc/cctk --PrimaryBattChargeCfg`

(which is what the plasmoid does if you untick the box), cctk refuses to run without being root. Apparently, cctk itself always checks to see if it is root when it is executed, and if not, it fails with the error. Some kind of privilege elevation (whether pkexec or sudo) is always needed.

I modified the plasmoid to use pkexec if the box is ticked and sudo if not, and changed the text to match, and also took out the bit where it sends the password when querying the status (I will post another issue about that), if you would like to use it as a reference (being that I have a Dell that can be used to test it and you don't!).

[cctk-batterycfg (3).tar.gz](https://github.com/enielrodriguez/cctk-batterycfg/files/13260115/cctk-batterycfg.3.tar.gz)

**Comment by enielrodriguez** [comment]
Ok, thanks, I appreciate it! I will integrate the changes as soon as I can.
