### ISSUE TITLE
Unable to query status with password set

### ISSUE THREAD

**Issue by TID41** [enielrodriguez/cctk-batterycfg#9]
The plasmoid attempts to send this command to query the status of the battery limit when the BIOS password is set in the plasmoid settings:

`/opt/dell/dcc/cctk --ValSetupPwd=xxxxxx --PrimaryBattChargeCfg`

(where xxxxxx is the password)

It generates this error:

Report operations and set operations must be separate.

The password is not needed to query the status, so the simplest way to fix it is to simply not send it when querying (as in the modified plasmoid I sent). Alternately, if the password statement is moved to the end, it will work:

`/opt/dell/dcc/cctk --PrimaryBattChargeCfg --ValSetupPwd=xxxxxx `

**Comment by enielrodriguez** [comment]
Hi! Thanks for the contribution. I will make the appropriate changes.
